package hardened_alloc

import "base:runtime"
import "core:mem"
import "core:mem/virtual"


Allocator :: runtime.Allocator
Allocator_Error :: runtime.Allocator_Error
Allocator_Mode :: runtime.Allocator_Mode
Allocator_Mode_Set :: runtime.Allocator_Mode_Set
Allocator_Query_Info :: runtime.Allocator_Query_Info


DEFAULT_ALIGNMENT :: mem.DEFAULT_ALIGNMENT
SIZE_CLASS_COUNT :: 16
TYPE_BUCKET_COUNT :: 16
MIN_SIZE_CLASS :: 32
MIN_SPLIT_PAYLOAD :: 16
DEFAULT_REGION_SIZE :: mem.DEFAULT_PAGE_SIZE * 4
MAX_RECURSION_DEPTH :: 16
DEFAULT_QUARANTINE_SIZE :: 10

typed_new :: proc(
	$T: typeid,
	alignment := align_of(T),
	allocator := context.allocator,
	loc := #caller_location,
) -> (
	^T,
	Allocator_Error,
) {
	if allocator.procedure == hardened_allocator_proc {
		raw, err := hardened_allocator_alloc(cast(^Hardened_Allocator)allocator.data, T, alignment)
		if err != nil {
			return nil, err
		}
		return cast(^T)raw, nil
	}
	return mem.new_aligned(T, alignment, allocator, loc)

}

manual_entry :: proc($T: typeid, class: Type_Class) -> Manual_Type_Entry {
	return Manual_Type_Entry{id = typeid_of(T), class = class}
}

_free_memory :: proc(bytes: []byte) -> Allocator_Error {
	virtual.release(raw_data(bytes), uint(len(bytes)))
	return nil
}

@(require_results)
_request_memory :: proc "contextless" (size: int) -> ([]byte, mem.Allocator_Error) {
	if size <= 0 {
		return nil, nil
	}

	bytes, err := virtual.reserve_and_commit(uint(size))
	if err != nil {
		return nil, err
	}

	return bytes, nil
}


// The following non-cryptographic rolling hash functions were generated by ChatGPT
// https://chatgpt.com/share/6a06b2b0-3c40-83eb-ab74-ce53697d604c
HASH_OFFSET :: u64(14695981039346656037)
HASH_PRIME :: u64(1099511628211)

hash_add_int :: proc(hash: ^u64, value: int) {
	hash^ = (hash^ ~ u64(value)) * HASH_PRIME
}

hash_add_token :: proc(hash: ^u64, token: Signature_Token) {
	hash_add_int(hash, int(token))
}
