package hardened_alloc

import "base:runtime"
import "core:mem"

Allocator :: runtime.Allocator
Allocator_Error :: runtime.Allocator_Error
Allocator_Mode :: runtime.Allocator_Mode
Allocator_Mode_Set :: runtime.Allocator_Mode_Set
Allocator_Query_Info :: runtime.Allocator_Query_Info


DEFAULT_ALIGNMENT :: mem.DEFAULT_ALIGNMENT
SIZE_CLASS_COUNT :: 32
TYPE_BUCKET_COUNT :: 16
MIN_SIZE_CLASS :: 32
MIN_SPLIT_PAYLOAD :: 16
DEFAULT_REGION_SIZE :: 64 * mem.DEFAULT_PAGE_SIZE
MAX_RECURSION_DEPTH :: 16

manual_entry :: proc($T: typeid, class: Type_Class) -> Manual_Type_Entry {
	return Manual_Type_Entry{id = typeid_of(T), class = class}
}


// The following non-cryptographic rolling hash functions were generated by ChatGPT
// https://chatgpt.com/share/6a06b2b0-3c40-83eb-ab74-ce53697d604c
HASH_OFFSET :: u64(14695981039346656037)
HASH_PRIME :: u64(1099511628211)

hash_add_int :: proc(hash: ^u64, value: int) {
	hash^ = (hash^ ~ u64(value)) * HASH_PRIME
}

hash_add_token :: proc(hash: ^u64, token: Signature_Token) {
	hash_add_int(hash, int(token))
}
